import { Tool, ToolConfig } from '@/features/tools/types';

export const TOOLS: Tool[] = [
  {
    id: 'json',
    name: 'JSON整形ツール',
    number: '1',
    description: 'JSONデータの整形・検証・最小化をシンタックスハイライト付きで',
    icon: '{}',
    category: 'データ処理',
    badge: '人気',
    href: '/tools/json',
  },
  {
    id: 'base64',
    name: 'Base64エンコーダー',
    number: '2',
    description: 'テキストをBase64に変換、またはBase64文字列をテキストに変換',
    icon: '🔤',
    category: 'エンコーディング',
    badge: '実用',
    href: '/tools/base64',
  },
  {
    id: 'url',
    name: 'URLエンコーダー',
    number: '3',
    description: 'URLの安全なエンコード・デコードを行います',
    icon: '🌐',
    category: 'エンコーディング',
    badge: '実用',
    href: '/tools/url-encoder',
  },
  {
    id: 'hash',
    name: 'ハッシュ生成器',
    number: '4',
    description: 'MD5、SHA-1、SHA-256、SHA-512のハッシュ値を生成',
    icon: '#',
    category: '暗号化',
    badge: 'セキュリティ',
    href: '/tools/hash-generator',
  },
  {
    id: 'regex',
    name: '正規表現テスター',
    number: '5',
    description: '正規表現をテストし、リアルタイムでマッチ結果を確認',
    icon: '.*',
    category: 'テキスト処理',
    badge: '開発',
    href: '/tools/regex',
  },
  {
    id: 'color',
    name: 'カラーパレット生成',
    number: '6',
    description: '調和の取れた美しいカラーパレットを自動生成',
    icon: '🎨',
    category: 'デザイン',
    badge: 'クリエイティブ',
    href: '/tools/color',
  },
  {
    id: 'qr',
    name: 'QRコード生成器',
    number: '7',
    description: 'テキストやURLから簡単にQRコードを生成',
    icon: '▦',
    category: 'ユーティリティ',
    badge: '便利',
    href: '/tools/qr',
  },
  {
    id: 'password',
    name: 'パスワード生成器',
    number: '8',
    description: 'カスタム条件で安全なパスワードを生成',
    icon: '🔐',
    category: 'セキュリティ',
    badge: 'セキュリティ',
    href: '/tools/password',
  },
  {
    id: 'timestamp',
    name: 'タイムスタンプ変換',
    number: '9',
    description: 'Unixタイムスタンプと日時の相互変換',
    icon: '⏰',
    category: 'ユーティリティ',
    badge: '実用',
    href: '/tools/timestamp',
  },
  {
    id: 'lorem',
    name: 'ダミーテキスト生成',
    number: '10',
    description: 'デザインや開発用のプレースホルダーテキストを生成',
    icon: '📝',
    category: 'コンテンツ',
    badge: 'デザイン',
    href: '/tools/lorem',
  },
  {
    id: 'jwt',
    name: 'JWT Decoder',
    number: '11',
    description: 'JSON Web Tokenのデコード・検証・解析',
    icon: '🔓',
    category: 'セキュリティ',
    badge: '開発',
    href: '/tools/jwt',
  },
  {
    id: 'sql',
    name: 'SQL Formatter',
    number: '12',
    description: 'SQLクエリの整形・最適化・検証',
    icon: '🗃️',
    category: 'データベース',
    badge: '開発',
    href: '/tools/sql',
  },
  {
    id: 'markdown',
    name: 'Markdown Preview',
    number: '13',
    description: 'Markdownのリアルタイムプレビューとエクスポート',
    icon: '📄',
    category: 'ドキュメント',
    badge: '実用',
    href: '/tools/markdown',
  },
  {
    id: 'uuid',
    name: 'UUID Generator',
    number: '14',
    description: 'UUID (v1/v4/v5) の生成・検証・一括生成',
    icon: '🆔',
    category: 'ユーティリティ',
    badge: '開発',
    href: '/tools/uuid',
  },
  {
    id: 'cron',
    name: 'Cron Expression Generator',
    number: '15',
    description: 'Cron式のビジュアル生成と次回実行時刻の確認',
    icon: '⏱️',
    category: 'ユーティリティ',
    badge: '実用',
    href: '/tools/cron',
  },
  {
    id: 'ascii',
    name: 'ASCII Art Generator',
    number: '16',
    description: 'テキストや画像からASCIIアートを生成',
    icon: '🎨',
    category: 'アート',
    badge: 'クリエイティブ',
    href: '/tools/ascii',
  },
  {
    id: 'diff',
    name: 'Diff Checker',
    number: '17',
    description: '2つのテキストの差分を視覚的に比較',
    icon: '🔍',
    category: 'テキスト処理',
    badge: '開発',
    href: '/tools/diff',
  },
  {
    id: 'xml',
    name: 'XML Formatter',
    number: '18',
    description: 'XMLの整形・検証・JSON変換',
    icon: '📄',
    category: 'データ処理',
    badge: '実用',
    href: '/tools/xml',
  },
  {
    id: 'csv-json',
    name: 'CSV ⇄ JSON Converter',
    number: '19',
    description: 'CSV形式とJSON形式のデータを相互変換',
    icon: '🔄',
    category: 'データ処理',
    badge: '実用',
    href: '/tools/csv-json',
  },
  {
    id: 'image',
    name: 'Image Compressor',
    number: '20',
    description: '画像圧縮・リサイズ・WebP変換',
    icon: '🖼️',
    category: 'ファイル処理',
    badge: '実用',
    href: '/tools/image',
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    number: '21',
    description: 'リアルタイムプレビュー付きMarkdownエディター',
    icon: '✏️',
    category: 'エディター',
    badge: '実用',
    href: '/tools/markdown-editor',
  },
  {
    id: 'html-css',
    name: 'HTML/CSS Beautifier',
    number: '22',
    description: 'HTML/CSSコードの整形と最適化',
    icon: '🎨',
    category: 'コード整形',
    badge: '実用',
    href: '/tools/html-css',
  },
];

export const TOOL_CONFIGS: ToolConfig[] = TOOLS.map((tool) => ({
  id: tool.id,
  name: tool.name,
  description: tool.description,
  icon: tool.icon,
}));
